# Generated by Django 2.0.4 on 2018-05-05 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180505_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
